---
# Site Settings
title: Heron's Buffer
description: >-
  Buffer place for my software development blogs. Mature ones are published at https://blog.heron.me.
email: heron.yang.tw@gmail.com
github_username: heronyang

---
# Build Settings
markdown: kramdown
theme: jekyll-theme-minimal
