title: Heron's Buffer
description: >-
  Buffer place for my software development blogs. Mature ones are published at Medium.
url: "https://buffer.heron.me"

theme: minima
plugins:
  - jekyll-archives
